---
name: Build to Docker Hub

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build & publish the project
        run: mvn compile jib:build -X -DjibSerialize=true
      - name: Bruno CLI runner
        id: bru-cli
        uses: krummbar/bruno-run-action@main # (1)
        with:
            path: /pet-clinic-tests
            # env: integration
            output: output.json
            output-format: json
