name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B install --file pom.xml -Djacoco.skip=true -DdisableXmlReport=true
      - name: Bruno CLI runner
        id: bru-cli
        uses: krummbar/bruno-run-action@main
        with:
          path: /pet-clinic-tests
          # env: integration
          output: output.json
          output-format: json
